export { Navbar } from './navbar'
export { FlightInfo } from './flightInfo'
export { Schedule } from './shcedule'
export { Ticket } from './ticket'
export { Transportation } from './transportation'
export { Cuisine } from './cuisine'
export { Footer } from './footer'
